# Generated by Django 3.2.4 on 2021-08-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readStatus',
            field=models.BooleanField(default=False),
        ),
    ]
